# All general configurations will be under this header
general:
  output_directory: results  # The output directory to save the training progress and results
  experiment_id: test # The experiment id
  # The name of the model checkpoints directory to save the intermediate model checkpoints
  model_checkpoints_directory_name: checkpoints

# All configurations related to dataloader will be under this header
dataloader:
  name: cub_200_2011  # Name of the dataloader to be used
  download: True  # Flag in order to decide if to download the dataset or not
  root_directory_path: ./data/CUB_200_2011  # The root directory path of the dataset
  resize_width: 448  # Image resize width
  resize_height: 448  # Image resize height
  batch_size: 8  # Batch size for training and testing
  shuffle: True  # Either to shuffle the dataset for training or not
  num_workers: 8  # Number of parallel workers to load the dataset
  # The train and test data transforms
  transforms:
    # Train transforms used during training
    train:
      t_1:
        path: torchvision.transforms.RandomHorizontalFlip
      t_2:
        path: torchvision.transforms.ToTensor
      t_3:
        path: torchvision.transforms.Normalize
        param:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    # Test transforms used during testing
    test:
      t_1:
        path: torchvision.transforms.ToTensor
      t_2:
        path: torchvision.transforms.Normalize
        param:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

# All configurations related to model will be under this header
model:
  name: fgvc_ssl_rotation  # Name/source of the model
  # Complete model class path (i.e. torchvision.models.resnet50, torchvision.models.alexnet, etc.)
  model_function_path: torchvision.models.resnet50
  pretrained: True  # Either to load weights from pretrained imagenet model
  classes_count: 200  # Number of classes
  rotation_classes_count: 4  # Number of rotation classes

# Configuration related to the diversification block will be under this head
diversification_block:
  patch_size: 3  # Patch size to be suppressed
  alpha: 0.1  # Suppression factor]

# All configurations related to training will be under this header
train:
  name: ssl_rot_trainer  # Name of the trainer to use
  epochs: 100  # Number of epochs
  warm_up_epochs: 10  # Number of warm up epochs
  warm_up_loss_function_path: torch.nn.CrossEntropyLoss  # Standard cross entropy loss
  class_loss_function_path: loss.gb_loss.GBLoss  # Loss function
  rotation_loss_function_path: torch.nn.CrossEntropyLoss  # Standard cross entropy loss for rotation prediction
  rotation_loss_weight: 0.5
  # Optimizer related configurations
  optimizer_path: torch.optim.SGD  # Complete optimizer class path
  optimizer_param:
    lr: 0.001  # Learning rate
    momentum: 0.9  # Momentum
    weight_decay: 0.0001  # Weight Decay
  # Learning rate scheduler configurations
  lr_scheduler:
    step_size: 50  # Step size
    gamma: 0.1  # Decay factor
