version: '3.7'

services:
  ssl_for_fgvc:
    image: mmaaz60/ssl_for_fgvc:v1.08
    volumes:
      - ./data:/workspace/data
      - ./config.yml:/workspace/config.yml
      - ./results:/workspace/results
    container_name: ssl_fgvc
    command: /bin/bash -c "python main.py"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    shm_size: '32gb'
    restart: on-failure
